[workspace]
members = ["runner"]

[package]
name = "sbc_algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
chunkfs = { path = "../chunkfs" } # change to " git = "

[dev-dependencies]
fastcdc = "3.1.0"
