[package]
name = "code_dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastcdc = "3.1.0"
memmap2 = "0.9.4"